### ISSUE TITLE
Actividad 7

### ISSUE THREAD

**Issue by SandyMarissaGs** [SistemasTecTlaxiaco/actividad-7-SandyMarissaGs#1]
[Linea Del Tiempo De La Web 1.0,2.0 y 3.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-SandyMarissaGs/files/9809783/Linea.Del.Tiempo.De.La.Web.1.0.2.0.y.3.0.pdf)

Sandy Marissa García Santiago grupo 1BS

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 7 "LINEA DEL TIEMPO DE LA WEB"
DE ACUERDO A LA RUBRICA OBTUVISTE ("17.2%") DEL 20% QUE EQUIVALE LA ACTIVIDAD.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
